server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      accept-empty: false
      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
